export const RANKS: { [key: string]: string } = {
  unranked: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_0.png',
  iron1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_3.png',
  iron2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_4.png',
  iron3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_5.png',
  bronze1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_6.png',
  bronze2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_7.png',
  bronze3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_8.png',
  silver1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_9.png',
  silver2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_10.png',
  silver3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_11.png',
  gold1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_12.png',
  gold2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_13.png',
  gold3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_14.png',
  platinum1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_15.png',
  platinum2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_16.png',
  platinum3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_17.png',
  diamond1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_18.png',
  diamond2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_19.png',
  diamond3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_20.png',
  ascendant1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_25.png',
  ascendant2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_26.png',
  ascendant3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_27.png',
  immortal1: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_21.png',
  immortal2: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_22.png',
  immortal3: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_23.png',
  radiant: '/CompetitiveTiers/Small/TX_CompetitiveTier_Small_24.png',
};